install_tool_dependencies: True
install_repository_dependencies: True
install_resolver_dependencies: True

tools:
- name: rename_tracks
  owner: yating-l
  revisions:
  - 72ccb2f848a0
  tool_panel_section_label: G-OnRamp Tools
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: trimmomatic
  owner: pjbriggs
  revisions:
  - 59054f086eca
  tool_panel_section_label: G-OnRamp Tools
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: fastqc
  owner: devteam
  revisions:
  - 3e1cdf5406db
  tool_panel_section_label: G-OnRamp Tools
  tool_shed_url: toolshed.g2.bx.psu.edu
- name: samtool_filter2
  owner: devteam
  revisions:
  - 56c31114ad4a
  tool_panel_section_label: G-OnRamp Tools
  tool_shed_url: toolshed.g2.bx.psu.edu
